"""add container and container_metric tables

Revision ID: 9dbc427e1870
Revises: e6118f377288
Create Date: 2026-07-27 12:29:49.296048

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9dbc427e1870"
down_revision: str | Sequence[str] | None = "e6118f377288"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "container",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("docker_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("image", sa.String(length=255), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "CREATED",
                "RUNNING",
                "PAUSED",
                "RESTARTING",
                "REMOVING",
                "EXITED",
                "DEAD",
                name="containerstate",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("compose_project", sa.String(length=255), nullable=True),
        sa.Column("compose_service", sa.String(length=255), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host_id", "docker_id", name="uq_container_host_docker"),
    )
    op.create_table(
        "container_metric",
        sa.Column("container_id", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cpu_usage", sa.Float(), nullable=False),
        sa.Column("cpu_throttled_time", sa.BigInteger(), nullable=False),
        sa.Column("memory_used", sa.BigInteger(), nullable=False),
        sa.Column("block_read", sa.BigInteger(), nullable=False),
        sa.Column("block_write", sa.BigInteger(), nullable=False),
        sa.Column("pids", sa.Integer(), nullable=False),
        sa.Column("memory_limit", sa.BigInteger(), nullable=True),
        sa.Column("net_rx", sa.BigInteger(), nullable=True),
        sa.Column("net_tx", sa.BigInteger(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("container_id", "collected_at"),
    )
    op.create_index(
        "ix_container_metric_collected_at",
        "container_metric",
        ["collected_at"],
        unique=False,
        postgresql_using="brin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_container_metric_collected_at",
        table_name="container_metric",
        postgresql_using="brin",
    )
    op.drop_table("container_metric")
    op.drop_table("container")
    # ### end Alembic commands ###
