"""empty message

Revision ID: e6118f377288
Revises:
Create Date: 2026-07-21 01:18:22.738316

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e6118f377288"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "host",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("agent_uuid", sa.Uuid(), nullable=False),
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ONLINE", "OFFLINE", name="hoststatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_uuid"),
    )
    op.create_table(
        "host_metric",
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cpu_usage", sa.Float(), nullable=False),
        sa.Column("memory_used", sa.BigInteger(), nullable=False),
        sa.Column("memory_total", sa.BigInteger(), nullable=False),
        sa.Column("disk_used", sa.BigInteger(), nullable=False),
        sa.Column("disk_total", sa.BigInteger(), nullable=False),
        sa.Column("net_rx", sa.BigInteger(), nullable=False),
        sa.Column("net_tx", sa.BigInteger(), nullable=False),
        sa.Column("load_avg_1", sa.Float(), nullable=True),
        sa.Column("load_avg_5", sa.Float(), nullable=True),
        sa.Column("load_avg_15", sa.Float(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("host_id", "collected_at"),
    )
    op.create_index(
        "ix_host_metric_collected_at",
        "host_metric",
        ["collected_at"],
        unique=False,
        postgresql_using="brin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_host_metric_collected_at", table_name="host_metric", postgresql_using="brin"
    )
    op.drop_table("host_metric")
    op.drop_table("host")
    # ### end Alembic commands ###
